SELECT LEAST(TRUNC(TO_DATE('17-06-19 12:35 PM', 'DD-MM-YY HH:MI PM')), TRUNC(SYSDATE)) AS nearest_lowest_date FROM dual;
SELECT LEAST(TRUNC(TO_DATE('17-06-19 12:35 AM', 'DD-MM-YY HH:MI AM')), TRUNC(SYSDATE)) AS nearest_lowest_date FROM dual;
SELECT LEAST(TRUNC(TO_DATE('17-06-19 01:30 PM', 'DD-MM-YY HH:MI PM')), TRUNC(SYSDATE)) AS nearest_lowest_date FROM dual;